Vagrant.configure("2") do |config|
  # Configuración de los servidores web Apache
  (1..2).each do |i|
    config.vm.define "web#{i}" do |web|
      web.vm.box = "ubuntu/bionic64"
      web.vm.hostname = "web#{i}"
      web.vm.network "private_network", ip: "192.168.33.1#{i}"
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      web.vm.synced_folder "./web", "/var/www/html"
      web.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y apache2
        echo "<h1>Servidor Web#{i}</h1>" | sudo tee /var/www/html/index.html
        sudo systemctl restart apache2
      SHELL
    end
  end

  # Configuración del servidor Nginx con balanceo de carga
  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "ubuntu/bionic64"
    nginx.vm.hostname = "nginx"
    nginx.vm.network "private_network", ip: "192.168.33.100"
    nginx.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    nginx.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y nginx
      sudo tee /etc/nginx/conf.d/load_balancer.conf > /dev/null <<EOF
      upstream backend {
          server 192.168.33.11;
          server 192.168.33.12;
      }

      server {
          listen 80;
          location / {
              proxy_pass http://backend;
          }
      }
      EOF
      sudo systemctl restart nginx
    SHELL
  end
end
